require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - config/**/*
    - db/**/*
    - bin/*
    - vendor/**/*
    - tmp/**/*

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
